Update comment_and_notify_event.yml

diff --git a/.github/workflows/comment_and_notify_event.yml b/.github/workflows/comment_and_notify_event.yml
--- a/.github/workflows/comment_and_notify_event.yml
+++ b/.github/workflows/comment_and_notify_event.yml
@@ -2,7 +2,7 @@ name: CICD Comment & Notify
 
 on:
   issue_comment:
-    types: [edited]
+    types: [created]
     
 env:
   MY_ACCOUNT: DEFAULT_ACCOUNT
@@ -47,7 +47,7 @@ jobs:
           echo "ENTORNO: " $MY_ENV
           export MY_IMAGE=${{ steps.split.outputs._6 }}
           echo "IMAGEN: " $MY_IMAGE
-          curl -d "{\"event_type\": \"test_result\", \"client_payload\":{\"account\":\"$MY_ACCOUNT\",\"environment\":\"$MY_ENV\",\"image\":\"$MY_IMAGE\"}}" -H "Content-Type:application/json" -H "Authorization:token $REPO_TOKEN" -H "Accept:application/vnd.github.everest-preview+json" "https://api.github.com/repos/$ORG/$REPO/dispatches"
+#           curl -d "{\"event_type\": \"test_result\", \"client_payload\":{\"account\":\"$MY_ACCOUNT\",\"environment\":\"$MY_ENV\",\"image\":\"$MY_IMAGE\"}}" -H "Content-Type:application/json" -H "Authorization:token $REPO_TOKEN" -H "Accept:application/vnd.github.everest-preview+json" "https://api.github.com/repos/$ORG/$REPO/dispatches"
       - id: get_env_and_latest_image
         name: get_env_and_latest_image
         if: steps.split.outputs._0 == '/deploy' && steps.split.outputs._1 == '--account' && steps.split.outputs._3 == '--env' && steps.split.outputs._5 != '--image'
@@ -59,32 +59,32 @@ jobs:
           export MY_ENV=${{ steps.split.outputs._2 }}
           echo "ENTORNO: " $MY_ENV
           echo "IMAGEN: " $MY_IMAGE  
-          curl -d "{\"event_type\": \"test_result\", \"client_payload\":{\"account\":\"$MY_ACCOUNT\",\"environment\":\"$MY_ENV\",\"image\":\"$MY_IMAGE\"}}" -H "Content-Type:application/json" -H "Authorization:token $REPO_TOKEN" -H "Accept:application/vnd.github.everest-preview+json" "https://api.github.com/repos/$ORG/$REPO/dispatches"
-      - name: Fail randomly
-        run: |
-          ls
-          exit $((RANDOM % 2))        
-      - name: Message success
-        if: ${{ success() }}
-        uses: actions/github-script@v4
-        with:
-          script: |
-            process.env.FINAL_MESSAGE='Deployment succeeded! ✅';
-            github.issues.createComment({
-              issue_number: context.issue.number,
-              owner: context.repo.owner,
-              repo: context.repo.repo,
-              body: process.env.FINAL_MESSAGE,
-            });          
-      - name: Message failure
-        if: ${{ failure() }}
-        uses: actions/github-script@v4
-        with:
-          script: |
-            process.env.FINAL_MESSAGE='Deployment failed! ❌';
-            github.issues.createComment({
-              issue_number: context.issue.number,
-              owner: context.repo.owner,
-              repo: context.repo.repo,
-              body: process.env.FINAL_MESSAGE,
-              }); 
+#           curl -d "{\"event_type\": \"test_result\", \"client_payload\":{\"account\":\"$MY_ACCOUNT\",\"environment\":\"$MY_ENV\",\"image\":\"$MY_IMAGE\"}}" -H "Content-Type:application/json" -H "Authorization:token $REPO_TOKEN" -H "Accept:application/vnd.github.everest-preview+json" "https://api.github.com/repos/$ORG/$REPO/dispatches"
+#       - name: Fail randomly
+#         run: |
+#           ls
+#           exit $((RANDOM % 2))        
+#       - name: Message success
+#         if: ${{ success() }}
+#         uses: actions/github-script@v4
+#         with:
+#           script: |
+#             process.env.FINAL_MESSAGE='Deployment succeeded! ✅';
+#             github.issues.createComment({
+#               issue_number: context.issue.number,
+#               owner: context.repo.owner,
+#               repo: context.repo.repo,
+#               body: process.env.FINAL_MESSAGE,
+#             });          
+#       - name: Message failure
+#         if: ${{ failure() }}
+#         uses: actions/github-script@v4
+#         with:
+#           script: |
+#             process.env.FINAL_MESSAGE='Deployment failed! ❌';
+#             github.issues.createComment({
+#               issue_number: context.issue.number,
+#               owner: context.repo.owner,
+#               repo: context.repo.repo,
+#               body: process.env.FINAL_MESSAGE,
+#               }); 
